// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: const.proto

package proto;

public final class ConstProto {
  private ConstProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *错误码
   * </pre>
   *
   * Protobuf enum {@code proto.Result}
   */
  public enum Result
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <pre>
     *服务空
     * </pre>
     *
     * <code>SERVER_NULL = 1;</code>
     */
    SERVER_NULL(1),
    /**
     * <pre>
     *回复超时
     * </pre>
     *
     * <code>TIME_OUT = 2;</code>
     */
    TIME_OUT(2),
    /**
     * <pre>
     *服务错误
     * </pre>
     *
     * <code>SERVER_ERROR = 3;</code>
     */
    SERVER_ERROR(3),
    /**
     * <pre>
     *桌子已经开始
     * </pre>
     *
     * <code>TABLE_START = 4;</code>
     */
    TABLE_START(4),
    /**
     * <pre>
     *桌子未开始
     * </pre>
     *
     * <code>TABLE_NOT_START = 5;</code>
     */
    TABLE_NOT_START(5),
    /**
     * <pre>
     *桌子配置错误
     * </pre>
     *
     * <code>TABLE_CONFIG_ERROR = 6;</code>
     */
    TABLE_CONFIG_ERROR(6),
    /**
     * <pre>
     *桌子空
     * </pre>
     *
     * <code>TABLE_NULL = 7;</code>
     */
    TABLE_NULL(7),
    /**
     * <pre>
     *桌子满
     * </pre>
     *
     * <code>TABLE_FULL = 8;</code>
     */
    TABLE_FULL(8),
    /**
     * <pre>
     *桌子异常
     * </pre>
     *
     * <code>TABLE_ERROR = 9;</code>
     */
    TABLE_ERROR(9),
    /**
     * <pre>
     *玩家异常
     * </pre>
     *
     * <code>ROLE_ERROR = 10;</code>
     */
    ROLE_ERROR(10),
    /**
     * <pre>
     *玩家空
     * </pre>
     *
     * <code>ROLE_NULL = 11;</code>
     */
    ROLE_NULL(11),
    /**
     * <pre>
     *当前操作位置没有操作
     * </pre>
     *
     * <code>OP_CURR_ERROR = 12;</code>
     */
    OP_CURR_ERROR(12),
    /**
     * <pre>
     *操作牌数不匹配
     * </pre>
     *
     * <code>OP_CARD_NOT_MATCH = 13;</code>
     */
    OP_CARD_NOT_MATCH(13),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <pre>
     *服务空
     * </pre>
     *
     * <code>SERVER_NULL = 1;</code>
     */
    public static final int SERVER_NULL_VALUE = 1;
    /**
     * <pre>
     *回复超时
     * </pre>
     *
     * <code>TIME_OUT = 2;</code>
     */
    public static final int TIME_OUT_VALUE = 2;
    /**
     * <pre>
     *服务错误
     * </pre>
     *
     * <code>SERVER_ERROR = 3;</code>
     */
    public static final int SERVER_ERROR_VALUE = 3;
    /**
     * <pre>
     *桌子已经开始
     * </pre>
     *
     * <code>TABLE_START = 4;</code>
     */
    public static final int TABLE_START_VALUE = 4;
    /**
     * <pre>
     *桌子未开始
     * </pre>
     *
     * <code>TABLE_NOT_START = 5;</code>
     */
    public static final int TABLE_NOT_START_VALUE = 5;
    /**
     * <pre>
     *桌子配置错误
     * </pre>
     *
     * <code>TABLE_CONFIG_ERROR = 6;</code>
     */
    public static final int TABLE_CONFIG_ERROR_VALUE = 6;
    /**
     * <pre>
     *桌子空
     * </pre>
     *
     * <code>TABLE_NULL = 7;</code>
     */
    public static final int TABLE_NULL_VALUE = 7;
    /**
     * <pre>
     *桌子满
     * </pre>
     *
     * <code>TABLE_FULL = 8;</code>
     */
    public static final int TABLE_FULL_VALUE = 8;
    /**
     * <pre>
     *桌子异常
     * </pre>
     *
     * <code>TABLE_ERROR = 9;</code>
     */
    public static final int TABLE_ERROR_VALUE = 9;
    /**
     * <pre>
     *玩家异常
     * </pre>
     *
     * <code>ROLE_ERROR = 10;</code>
     */
    public static final int ROLE_ERROR_VALUE = 10;
    /**
     * <pre>
     *玩家空
     * </pre>
     *
     * <code>ROLE_NULL = 11;</code>
     */
    public static final int ROLE_NULL_VALUE = 11;
    /**
     * <pre>
     *当前操作位置没有操作
     * </pre>
     *
     * <code>OP_CURR_ERROR = 12;</code>
     */
    public static final int OP_CURR_ERROR_VALUE = 12;
    /**
     * <pre>
     *操作牌数不匹配
     * </pre>
     *
     * <code>OP_CARD_NOT_MATCH = 13;</code>
     */
    public static final int OP_CARD_NOT_MATCH_VALUE = 13;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Result valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Result forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return SERVER_NULL;
        case 2: return TIME_OUT;
        case 3: return SERVER_ERROR;
        case 4: return TABLE_START;
        case 5: return TABLE_NOT_START;
        case 6: return TABLE_CONFIG_ERROR;
        case 7: return TABLE_NULL;
        case 8: return TABLE_FULL;
        case 9: return TABLE_ERROR;
        case 10: return ROLE_ERROR;
        case 11: return ROLE_NULL;
        case 12: return OP_CURR_ERROR;
        case 13: return OP_CARD_NOT_MATCH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Result>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Result> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Result>() {
            public Result findValueByNumber(int number) {
              return Result.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.ConstProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Result[] VALUES = values();

    public static Result valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Result(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.Result)
  }

  /**
   * <pre>
   *room状态
   * TODO: WAITE was renamed to WAIT. Regenerate Java code and update TableInfo.java references (ConstProto.TableState.WAITE -&gt; WAIT)
   * </pre>
   *
   * Protobuf enum {@code proto.TableState}
   */
  public enum TableState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *等待
     * </pre>
     *
     * <code>WAIT = 0;</code>
     */
    WAIT(0),
    /**
     * <pre>
     *开始
     * </pre>
     *
     * <code>START = 1;</code>
     */
    START(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *等待
     * </pre>
     *
     * <code>WAIT = 0;</code>
     */
    public static final int WAIT_VALUE = 0;
    /**
     * <pre>
     *开始
     * </pre>
     *
     * <code>START = 1;</code>
     */
    public static final int START_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TableState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TableState forNumber(int value) {
      switch (value) {
        case 0: return WAIT;
        case 1: return START;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TableState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TableState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TableState>() {
            public TableState findValueByNumber(int number) {
              return TableState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.ConstProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final TableState[] VALUES = values();

    public static TableState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TableState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.TableState)
  }

  /**
   * <pre>
   *操作选择
   * </pre>
   *
   * Protobuf enum {@code proto.Operation}
   */
  public enum Operation
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *过
     * </pre>
     *
     * <code>PASS = 0;</code>
     */
    PASS(0),
    /**
     * <pre>
     *叫地主(兼容)
     * </pre>
     *
     * <code>CALL = 1;</code>
     */
    CALL(1),
    /**
     * <pre>
     *抢地主
     * </pre>
     *
     * <code>ROB = 2;</code>
     */
    ROB(2),
    /**
     * <pre>
     *不叫地主
     * </pre>
     *
     * <code>NOT_CALL = 3;</code>
     */
    NOT_CALL(3),
    /**
     * <pre>
     *不抢地主
     * </pre>
     *
     * <code>NOT_ROB = 4;</code>
     */
    NOT_ROB(4),
    /**
     * <pre>
     *提示
     * </pre>
     *
     * <code>TIP = 5;</code>
     */
    TIP(5),
    /**
     * <pre>
     *出
     * </pre>
     *
     * <code>PLAY = 6;</code>
     */
    PLAY(6),
    /**
     * <pre>
     *准备
     * </pre>
     *
     * <code>PREPARE = 7;</code>
     */
    PREPARE(7),
    /**
     * <pre>
     *开始
     * </pre>
     *
     * <code>START_GAME = 8;</code>
     */
    START_GAME(8),
    /**
     * <pre>
     *叫一分
     * </pre>
     *
     * <code>CALL_SCORE_1 = 9;</code>
     */
    CALL_SCORE_1(9),
    /**
     * <pre>
     *叫二分
     * </pre>
     *
     * <code>CALL_SCORE_2 = 10;</code>
     */
    CALL_SCORE_2(10),
    /**
     * <pre>
     *叫三分
     * </pre>
     *
     * <code>CALL_SCORE_3 = 11;</code>
     */
    CALL_SCORE_3(11),
    /**
     * <pre>
     *摸牌(麻将)
     * </pre>
     *
     * <code>DRAW = 12;</code>
     */
    DRAW(12),
    /**
     * <pre>
     *出牌(麻将)
     * </pre>
     *
     * <code>DISCARD = 13;</code>
     */
    DISCARD(13),
    /**
     * <pre>
     *碰(麻将)
     * </pre>
     *
     * <code>MJ_PENG = 14;</code>
     */
    MJ_PENG(14),
    /**
     * <pre>
     *杠(麻将)
     * </pre>
     *
     * <code>MJ_GANG = 15;</code>
     */
    MJ_GANG(15),
    /**
     * <pre>
     *吃(麻将)
     * </pre>
     *
     * <code>MJ_CHI = 16;</code>
     */
    MJ_CHI(16),
    /**
     * <pre>
     *胡(麻将)
     * </pre>
     *
     * <code>MJ_HU = 17;</code>
     */
    MJ_HU(17),
    /**
     * <pre>
     *过(麻将)
     * </pre>
     *
     * <code>MJ_PASS = 18;</code>
     */
    MJ_PASS(18),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *过
     * </pre>
     *
     * <code>PASS = 0;</code>
     */
    public static final int PASS_VALUE = 0;
    /**
     * <pre>
     *叫地主(兼容)
     * </pre>
     *
     * <code>CALL = 1;</code>
     */
    public static final int CALL_VALUE = 1;
    /**
     * <pre>
     *抢地主
     * </pre>
     *
     * <code>ROB = 2;</code>
     */
    public static final int ROB_VALUE = 2;
    /**
     * <pre>
     *不叫地主
     * </pre>
     *
     * <code>NOT_CALL = 3;</code>
     */
    public static final int NOT_CALL_VALUE = 3;
    /**
     * <pre>
     *不抢地主
     * </pre>
     *
     * <code>NOT_ROB = 4;</code>
     */
    public static final int NOT_ROB_VALUE = 4;
    /**
     * <pre>
     *提示
     * </pre>
     *
     * <code>TIP = 5;</code>
     */
    public static final int TIP_VALUE = 5;
    /**
     * <pre>
     *出
     * </pre>
     *
     * <code>PLAY = 6;</code>
     */
    public static final int PLAY_VALUE = 6;
    /**
     * <pre>
     *准备
     * </pre>
     *
     * <code>PREPARE = 7;</code>
     */
    public static final int PREPARE_VALUE = 7;
    /**
     * <pre>
     *开始
     * </pre>
     *
     * <code>START_GAME = 8;</code>
     */
    public static final int START_GAME_VALUE = 8;
    /**
     * <pre>
     *叫一分
     * </pre>
     *
     * <code>CALL_SCORE_1 = 9;</code>
     */
    public static final int CALL_SCORE_1_VALUE = 9;
    /**
     * <pre>
     *叫二分
     * </pre>
     *
     * <code>CALL_SCORE_2 = 10;</code>
     */
    public static final int CALL_SCORE_2_VALUE = 10;
    /**
     * <pre>
     *叫三分
     * </pre>
     *
     * <code>CALL_SCORE_3 = 11;</code>
     */
    public static final int CALL_SCORE_3_VALUE = 11;
    /**
     * <pre>
     *摸牌(麻将)
     * </pre>
     *
     * <code>DRAW = 12;</code>
     */
    public static final int DRAW_VALUE = 12;
    /**
     * <pre>
     *出牌(麻将)
     * </pre>
     *
     * <code>DISCARD = 13;</code>
     */
    public static final int DISCARD_VALUE = 13;
    /**
     * <pre>
     *碰(麻将)
     * </pre>
     *
     * <code>MJ_PENG = 14;</code>
     */
    public static final int MJ_PENG_VALUE = 14;
    /**
     * <pre>
     *杠(麻将)
     * </pre>
     *
     * <code>MJ_GANG = 15;</code>
     */
    public static final int MJ_GANG_VALUE = 15;
    /**
     * <pre>
     *吃(麻将)
     * </pre>
     *
     * <code>MJ_CHI = 16;</code>
     */
    public static final int MJ_CHI_VALUE = 16;
    /**
     * <pre>
     *胡(麻将)
     * </pre>
     *
     * <code>MJ_HU = 17;</code>
     */
    public static final int MJ_HU_VALUE = 17;
    /**
     * <pre>
     *过(麻将)
     * </pre>
     *
     * <code>MJ_PASS = 18;</code>
     */
    public static final int MJ_PASS_VALUE = 18;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Operation valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Operation forNumber(int value) {
      switch (value) {
        case 0: return PASS;
        case 1: return CALL;
        case 2: return ROB;
        case 3: return NOT_CALL;
        case 4: return NOT_ROB;
        case 5: return TIP;
        case 6: return PLAY;
        case 7: return PREPARE;
        case 8: return START_GAME;
        case 9: return CALL_SCORE_1;
        case 10: return CALL_SCORE_2;
        case 11: return CALL_SCORE_3;
        case 12: return DRAW;
        case 13: return DISCARD;
        case 14: return MJ_PENG;
        case 15: return MJ_GANG;
        case 16: return MJ_CHI;
        case 17: return MJ_HU;
        case 18: return MJ_PASS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Operation>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Operation> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Operation>() {
            public Operation findValueByNumber(int number) {
              return Operation.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.ConstProto.getDescriptor().getEnumTypes().get(2);
    }

    private static final Operation[] VALUES = values();

    public static Operation valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Operation(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.Operation)
  }

  /**
   * <pre>
   *牌型
   * </pre>
   *
   * Protobuf enum {@code proto.CardType}
   */
  public enum CardType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *单
     * </pre>
     *
     * <code>SINGLE = 0;</code>
     */
    SINGLE(0),
    /**
     * <pre>
     *对子
     * </pre>
     *
     * <code>DOUBLE = 1;</code>
     */
    DOUBLE(1),
    /**
     * <pre>
     *三不带
     * </pre>
     *
     * <code>TRIPLE = 2;</code>
     */
    TRIPLE(2),
    /**
     * <pre>
     *三带一
     * </pre>
     *
     * <code>TRIPLE_ONE = 3;</code>
     */
    TRIPLE_ONE(3),
    /**
     * <pre>
     *三带二
     * </pre>
     *
     * <code>TRIPLE_DOUBLE = 4;</code>
     */
    TRIPLE_DOUBLE(4),
    /**
     * <pre>
     *飞机带一
     * </pre>
     *
     * <code>PLANE_ONE = 5;</code>
     */
    PLANE_ONE(5),
    /**
     * <pre>
     *飞机带二
     * </pre>
     *
     * <code>PLANE_DOUBLE = 6;</code>
     */
    PLANE_DOUBLE(6),
    /**
     * <pre>
     *炸弹带二单
     * </pre>
     *
     * <code>BOOM_DOUBLE_SINGLE = 7;</code>
     */
    BOOM_DOUBLE_SINGLE(7),
    /**
     * <pre>
     *炸弹带二对  // renamed from BOOM_DOUBLE_CUP (CUP was unclear)
     * </pre>
     *
     * <code>BOOM_DOUBLE_PAIR = 8;</code>
     */
    BOOM_DOUBLE_PAIR(8),
    /**
     * <pre>
     *顺子
     * </pre>
     *
     * <code>STRAIGHT = 9;</code>
     */
    STRAIGHT(9),
    /**
     * <pre>
     *连对子
     * </pre>
     *
     * <code>STRAIGHT_DOUBLE = 10;</code>
     */
    STRAIGHT_DOUBLE(10),
    /**
     * <pre>
     *炸弹
     * </pre>
     *
     * <code>BOOM = 11;</code>
     */
    BOOM(11),
    /**
     * <pre>
     *双王炸
     * </pre>
     *
     * <code>BOOM_MAX = 12;</code>
     */
    BOOM_MAX(12),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *单
     * </pre>
     *
     * <code>SINGLE = 0;</code>
     */
    public static final int SINGLE_VALUE = 0;
    /**
     * <pre>
     *对子
     * </pre>
     *
     * <code>DOUBLE = 1;</code>
     */
    public static final int DOUBLE_VALUE = 1;
    /**
     * <pre>
     *三不带
     * </pre>
     *
     * <code>TRIPLE = 2;</code>
     */
    public static final int TRIPLE_VALUE = 2;
    /**
     * <pre>
     *三带一
     * </pre>
     *
     * <code>TRIPLE_ONE = 3;</code>
     */
    public static final int TRIPLE_ONE_VALUE = 3;
    /**
     * <pre>
     *三带二
     * </pre>
     *
     * <code>TRIPLE_DOUBLE = 4;</code>
     */
    public static final int TRIPLE_DOUBLE_VALUE = 4;
    /**
     * <pre>
     *飞机带一
     * </pre>
     *
     * <code>PLANE_ONE = 5;</code>
     */
    public static final int PLANE_ONE_VALUE = 5;
    /**
     * <pre>
     *飞机带二
     * </pre>
     *
     * <code>PLANE_DOUBLE = 6;</code>
     */
    public static final int PLANE_DOUBLE_VALUE = 6;
    /**
     * <pre>
     *炸弹带二单
     * </pre>
     *
     * <code>BOOM_DOUBLE_SINGLE = 7;</code>
     */
    public static final int BOOM_DOUBLE_SINGLE_VALUE = 7;
    /**
     * <pre>
     *炸弹带二对  // renamed from BOOM_DOUBLE_CUP (CUP was unclear)
     * </pre>
     *
     * <code>BOOM_DOUBLE_PAIR = 8;</code>
     */
    public static final int BOOM_DOUBLE_PAIR_VALUE = 8;
    /**
     * <pre>
     *顺子
     * </pre>
     *
     * <code>STRAIGHT = 9;</code>
     */
    public static final int STRAIGHT_VALUE = 9;
    /**
     * <pre>
     *连对子
     * </pre>
     *
     * <code>STRAIGHT_DOUBLE = 10;</code>
     */
    public static final int STRAIGHT_DOUBLE_VALUE = 10;
    /**
     * <pre>
     *炸弹
     * </pre>
     *
     * <code>BOOM = 11;</code>
     */
    public static final int BOOM_VALUE = 11;
    /**
     * <pre>
     *双王炸
     * </pre>
     *
     * <code>BOOM_MAX = 12;</code>
     */
    public static final int BOOM_MAX_VALUE = 12;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CardType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static CardType forNumber(int value) {
      switch (value) {
        case 0: return SINGLE;
        case 1: return DOUBLE;
        case 2: return TRIPLE;
        case 3: return TRIPLE_ONE;
        case 4: return TRIPLE_DOUBLE;
        case 5: return PLANE_ONE;
        case 6: return PLANE_DOUBLE;
        case 7: return BOOM_DOUBLE_SINGLE;
        case 8: return BOOM_DOUBLE_PAIR;
        case 9: return STRAIGHT;
        case 10: return STRAIGHT_DOUBLE;
        case 11: return BOOM;
        case 12: return BOOM_MAX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CardType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        CardType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CardType>() {
            public CardType findValueByNumber(int number) {
              return CardType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.ConstProto.getDescriptor().getEnumTypes().get(3);
    }

    private static final CardType[] VALUES = values();

    public static CardType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private CardType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.CardType)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013const.proto\022\005proto*\376\001\n\006Result\022\013\n\007SUCCE" +
      "SS\020\000\022\017\n\013SERVER_NULL\020\001\022\014\n\010TIME_OUT\020\002\022\020\n\014S" +
      "ERVER_ERROR\020\003\022\017\n\013TABLE_START\020\004\022\023\n\017TABLE_" +
      "NOT_START\020\005\022\026\n\022TABLE_CONFIG_ERROR\020\006\022\016\n\nT" +
      "ABLE_NULL\020\007\022\016\n\nTABLE_FULL\020\010\022\017\n\013TABLE_ERR" +
      "OR\020\t\022\016\n\nROLE_ERROR\020\n\022\r\n\tROLE_NULL\020\013\022\021\n\rO" +
      "P_CURR_ERROR\020\014\022\025\n\021OP_CARD_NOT_MATCH\020\r*!\n" +
      "\nTableState\022\010\n\004WAIT\020\000\022\t\n\005START\020\001*\376\001\n\tOpe" +
      "ration\022\010\n\004PASS\020\000\022\010\n\004CALL\020\001\022\007\n\003ROB\020\002\022\014\n\010N" +
      "OT_CALL\020\003\022\013\n\007NOT_ROB\020\004\022\007\n\003TIP\020\005\022\010\n\004PLAY\020" +
      "\006\022\013\n\007PREPARE\020\007\022\016\n\nSTART_GAME\020\010\022\020\n\014CALL_S" +
      "CORE_1\020\t\022\020\n\014CALL_SCORE_2\020\n\022\020\n\014CALL_SCORE" +
      "_3\020\013\022\010\n\004DRAW\020\014\022\013\n\007DISCARD\020\r\022\013\n\007MJ_PENG\020\016" +
      "\022\013\n\007MJ_GANG\020\017\022\n\n\006MJ_CHI\020\020\022\t\n\005MJ_HU\020\021\022\013\n\007" +
      "MJ_PASS\020\022*\333\001\n\010CardType\022\n\n\006SINGLE\020\000\022\n\n\006DO" +
      "UBLE\020\001\022\n\n\006TRIPLE\020\002\022\016\n\nTRIPLE_ONE\020\003\022\021\n\rTR" +
      "IPLE_DOUBLE\020\004\022\r\n\tPLANE_ONE\020\005\022\020\n\014PLANE_DO" +
      "UBLE\020\006\022\026\n\022BOOM_DOUBLE_SINGLE\020\007\022\024\n\020BOOM_D" +
      "OUBLE_PAIR\020\010\022\014\n\010STRAIGHT\020\t\022\023\n\017STRAIGHT_D" +
      "OUBLE\020\n\022\010\n\004BOOM\020\013\022\014\n\010BOOM_MAX\020\014B\014B\nConst" +
      "Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
