// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

package proto;

public final class GameProto {
  private GameProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqEnterTableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ReqEnterTable)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 tableId = 1;</code>
     */
    int getTableId();

    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    java.util.List<proto.ModelProto.KeyValue> 
        getAppendList();
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    proto.ModelProto.KeyValue getAppend(int index);
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    int getAppendCount();
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    java.util.List<? extends proto.ModelProto.KeyValueOrBuilder> 
        getAppendOrBuilderList();
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    proto.ModelProto.KeyValueOrBuilder getAppendOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.ReqEnterTable}
   */
  public  static final class ReqEnterTable extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ReqEnterTable)
      ReqEnterTableOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqEnterTable.newBuilder() to construct.
    private ReqEnterTable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqEnterTable() {
      tableId_ = 0;
      append_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqEnterTable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              tableId_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                append_ = new java.util.ArrayList<proto.ModelProto.KeyValue>();
                mutable_bitField0_ |= 0x00000002;
              }
              append_.add(
                  input.readMessage(proto.ModelProto.KeyValue.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          append_ = java.util.Collections.unmodifiableList(append_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.GameProto.internal_static_proto_ReqEnterTable_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.GameProto.internal_static_proto_ReqEnterTable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GameProto.ReqEnterTable.class, proto.GameProto.ReqEnterTable.Builder.class);
    }

    private int bitField0_;
    public static final int TABLEID_FIELD_NUMBER = 1;
    private int tableId_;
    /**
     * <code>int32 tableId = 1;</code>
     */
    public int getTableId() {
      return tableId_;
    }

    public static final int APPEND_FIELD_NUMBER = 2;
    private java.util.List<proto.ModelProto.KeyValue> append_;
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    public java.util.List<proto.ModelProto.KeyValue> getAppendList() {
      return append_;
    }
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    public java.util.List<? extends proto.ModelProto.KeyValueOrBuilder> 
        getAppendOrBuilderList() {
      return append_;
    }
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    public int getAppendCount() {
      return append_.size();
    }
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    public proto.ModelProto.KeyValue getAppend(int index) {
      return append_.get(index);
    }
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    public proto.ModelProto.KeyValueOrBuilder getAppendOrBuilder(
        int index) {
      return append_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tableId_ != 0) {
        output.writeInt32(1, tableId_);
      }
      for (int i = 0; i < append_.size(); i++) {
        output.writeMessage(2, append_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tableId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, tableId_);
      }
      for (int i = 0; i < append_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, append_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.GameProto.ReqEnterTable)) {
        return super.equals(obj);
      }
      proto.GameProto.ReqEnterTable other = (proto.GameProto.ReqEnterTable) obj;

      boolean result = true;
      result = result && (getTableId()
          == other.getTableId());
      result = result && getAppendList()
          .equals(other.getAppendList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TABLEID_FIELD_NUMBER;
      hash = (53 * hash) + getTableId();
      if (getAppendCount() > 0) {
        hash = (37 * hash) + APPEND_FIELD_NUMBER;
        hash = (53 * hash) + getAppendList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.GameProto.ReqEnterTable parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GameProto.ReqEnterTable parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GameProto.ReqEnterTable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GameProto.ReqEnterTable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GameProto.ReqEnterTable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GameProto.ReqEnterTable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GameProto.ReqEnterTable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GameProto.ReqEnterTable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GameProto.ReqEnterTable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.GameProto.ReqEnterTable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GameProto.ReqEnterTable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GameProto.ReqEnterTable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.GameProto.ReqEnterTable prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.ReqEnterTable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ReqEnterTable)
        proto.GameProto.ReqEnterTableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.GameProto.internal_static_proto_ReqEnterTable_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.GameProto.internal_static_proto_ReqEnterTable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.GameProto.ReqEnterTable.class, proto.GameProto.ReqEnterTable.Builder.class);
      }

      // Construct using proto.GameProto.ReqEnterTable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAppendFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        tableId_ = 0;

        if (appendBuilder_ == null) {
          append_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          appendBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.GameProto.internal_static_proto_ReqEnterTable_descriptor;
      }

      public proto.GameProto.ReqEnterTable getDefaultInstanceForType() {
        return proto.GameProto.ReqEnterTable.getDefaultInstance();
      }

      public proto.GameProto.ReqEnterTable build() {
        proto.GameProto.ReqEnterTable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.GameProto.ReqEnterTable buildPartial() {
        proto.GameProto.ReqEnterTable result = new proto.GameProto.ReqEnterTable(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.tableId_ = tableId_;
        if (appendBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            append_ = java.util.Collections.unmodifiableList(append_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.append_ = append_;
        } else {
          result.append_ = appendBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.GameProto.ReqEnterTable) {
          return mergeFrom((proto.GameProto.ReqEnterTable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.GameProto.ReqEnterTable other) {
        if (other == proto.GameProto.ReqEnterTable.getDefaultInstance()) return this;
        if (other.getTableId() != 0) {
          setTableId(other.getTableId());
        }
        if (appendBuilder_ == null) {
          if (!other.append_.isEmpty()) {
            if (append_.isEmpty()) {
              append_ = other.append_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAppendIsMutable();
              append_.addAll(other.append_);
            }
            onChanged();
          }
        } else {
          if (!other.append_.isEmpty()) {
            if (appendBuilder_.isEmpty()) {
              appendBuilder_.dispose();
              appendBuilder_ = null;
              append_ = other.append_;
              bitField0_ = (bitField0_ & ~0x00000002);
              appendBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAppendFieldBuilder() : null;
            } else {
              appendBuilder_.addAllMessages(other.append_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.GameProto.ReqEnterTable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.GameProto.ReqEnterTable) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int tableId_ ;
      /**
       * <code>int32 tableId = 1;</code>
       */
      public int getTableId() {
        return tableId_;
      }
      /**
       * <code>int32 tableId = 1;</code>
       */
      public Builder setTableId(int value) {
        
        tableId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 tableId = 1;</code>
       */
      public Builder clearTableId() {
        
        tableId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<proto.ModelProto.KeyValue> append_ =
        java.util.Collections.emptyList();
      private void ensureAppendIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          append_ = new java.util.ArrayList<proto.ModelProto.KeyValue>(append_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ModelProto.KeyValue, proto.ModelProto.KeyValue.Builder, proto.ModelProto.KeyValueOrBuilder> appendBuilder_;

      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public java.util.List<proto.ModelProto.KeyValue> getAppendList() {
        if (appendBuilder_ == null) {
          return java.util.Collections.unmodifiableList(append_);
        } else {
          return appendBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public int getAppendCount() {
        if (appendBuilder_ == null) {
          return append_.size();
        } else {
          return appendBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public proto.ModelProto.KeyValue getAppend(int index) {
        if (appendBuilder_ == null) {
          return append_.get(index);
        } else {
          return appendBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder setAppend(
          int index, proto.ModelProto.KeyValue value) {
        if (appendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppendIsMutable();
          append_.set(index, value);
          onChanged();
        } else {
          appendBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder setAppend(
          int index, proto.ModelProto.KeyValue.Builder builderForValue) {
        if (appendBuilder_ == null) {
          ensureAppendIsMutable();
          append_.set(index, builderForValue.build());
          onChanged();
        } else {
          appendBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder addAppend(proto.ModelProto.KeyValue value) {
        if (appendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppendIsMutable();
          append_.add(value);
          onChanged();
        } else {
          appendBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder addAppend(
          int index, proto.ModelProto.KeyValue value) {
        if (appendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppendIsMutable();
          append_.add(index, value);
          onChanged();
        } else {
          appendBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder addAppend(
          proto.ModelProto.KeyValue.Builder builderForValue) {
        if (appendBuilder_ == null) {
          ensureAppendIsMutable();
          append_.add(builderForValue.build());
          onChanged();
        } else {
          appendBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder addAppend(
          int index, proto.ModelProto.KeyValue.Builder builderForValue) {
        if (appendBuilder_ == null) {
          ensureAppendIsMutable();
          append_.add(index, builderForValue.build());
          onChanged();
        } else {
          appendBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder addAllAppend(
          java.lang.Iterable<? extends proto.ModelProto.KeyValue> values) {
        if (appendBuilder_ == null) {
          ensureAppendIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, append_);
          onChanged();
        } else {
          appendBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder clearAppend() {
        if (appendBuilder_ == null) {
          append_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          appendBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder removeAppend(int index) {
        if (appendBuilder_ == null) {
          ensureAppendIsMutable();
          append_.remove(index);
          onChanged();
        } else {
          appendBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public proto.ModelProto.KeyValue.Builder getAppendBuilder(
          int index) {
        return getAppendFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public proto.ModelProto.KeyValueOrBuilder getAppendOrBuilder(
          int index) {
        if (appendBuilder_ == null) {
          return append_.get(index);  } else {
          return appendBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public java.util.List<? extends proto.ModelProto.KeyValueOrBuilder> 
           getAppendOrBuilderList() {
        if (appendBuilder_ != null) {
          return appendBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(append_);
        }
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public proto.ModelProto.KeyValue.Builder addAppendBuilder() {
        return getAppendFieldBuilder().addBuilder(
            proto.ModelProto.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public proto.ModelProto.KeyValue.Builder addAppendBuilder(
          int index) {
        return getAppendFieldBuilder().addBuilder(
            index, proto.ModelProto.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public java.util.List<proto.ModelProto.KeyValue.Builder> 
           getAppendBuilderList() {
        return getAppendFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ModelProto.KeyValue, proto.ModelProto.KeyValue.Builder, proto.ModelProto.KeyValueOrBuilder> 
          getAppendFieldBuilder() {
        if (appendBuilder_ == null) {
          appendBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.ModelProto.KeyValue, proto.ModelProto.KeyValue.Builder, proto.ModelProto.KeyValueOrBuilder>(
                  append_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          append_ = null;
        }
        return appendBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ReqEnterTable)
    }

    // @@protoc_insertion_point(class_scope:proto.ReqEnterTable)
    private static final proto.GameProto.ReqEnterTable DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.GameProto.ReqEnterTable();
    }

    public static proto.GameProto.ReqEnterTable getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqEnterTable>
        PARSER = new com.google.protobuf.AbstractParser<ReqEnterTable>() {
      public ReqEnterTable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqEnterTable(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqEnterTable> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqEnterTable> getParserForType() {
      return PARSER;
    }

    public proto.GameProto.ReqEnterTable getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AckEnterTableOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.AckEnterTable)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 tableId = 1;</code>
     */
    int getTableId();

    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    java.util.List<proto.ModelProto.KeyValue> 
        getAppendList();
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    proto.ModelProto.KeyValue getAppend(int index);
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    int getAppendCount();
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    java.util.List<? extends proto.ModelProto.KeyValueOrBuilder> 
        getAppendOrBuilderList();
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    proto.ModelProto.KeyValueOrBuilder getAppendOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.AckEnterTable}
   */
  public  static final class AckEnterTable extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.AckEnterTable)
      AckEnterTableOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AckEnterTable.newBuilder() to construct.
    private AckEnterTable(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AckEnterTable() {
      tableId_ = 0;
      append_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AckEnterTable(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              tableId_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                append_ = new java.util.ArrayList<proto.ModelProto.KeyValue>();
                mutable_bitField0_ |= 0x00000002;
              }
              append_.add(
                  input.readMessage(proto.ModelProto.KeyValue.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          append_ = java.util.Collections.unmodifiableList(append_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.GameProto.internal_static_proto_AckEnterTable_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.GameProto.internal_static_proto_AckEnterTable_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GameProto.AckEnterTable.class, proto.GameProto.AckEnterTable.Builder.class);
    }

    private int bitField0_;
    public static final int TABLEID_FIELD_NUMBER = 1;
    private int tableId_;
    /**
     * <code>int32 tableId = 1;</code>
     */
    public int getTableId() {
      return tableId_;
    }

    public static final int APPEND_FIELD_NUMBER = 2;
    private java.util.List<proto.ModelProto.KeyValue> append_;
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    public java.util.List<proto.ModelProto.KeyValue> getAppendList() {
      return append_;
    }
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    public java.util.List<? extends proto.ModelProto.KeyValueOrBuilder> 
        getAppendOrBuilderList() {
      return append_;
    }
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    public int getAppendCount() {
      return append_.size();
    }
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    public proto.ModelProto.KeyValue getAppend(int index) {
      return append_.get(index);
    }
    /**
     * <code>repeated .proto.KeyValue append = 2;</code>
     */
    public proto.ModelProto.KeyValueOrBuilder getAppendOrBuilder(
        int index) {
      return append_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tableId_ != 0) {
        output.writeInt32(1, tableId_);
      }
      for (int i = 0; i < append_.size(); i++) {
        output.writeMessage(2, append_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tableId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, tableId_);
      }
      for (int i = 0; i < append_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, append_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.GameProto.AckEnterTable)) {
        return super.equals(obj);
      }
      proto.GameProto.AckEnterTable other = (proto.GameProto.AckEnterTable) obj;

      boolean result = true;
      result = result && (getTableId()
          == other.getTableId());
      result = result && getAppendList()
          .equals(other.getAppendList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TABLEID_FIELD_NUMBER;
      hash = (53 * hash) + getTableId();
      if (getAppendCount() > 0) {
        hash = (37 * hash) + APPEND_FIELD_NUMBER;
        hash = (53 * hash) + getAppendList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.GameProto.AckEnterTable parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GameProto.AckEnterTable parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GameProto.AckEnterTable parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GameProto.AckEnterTable parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GameProto.AckEnterTable parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GameProto.AckEnterTable parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GameProto.AckEnterTable parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GameProto.AckEnterTable parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GameProto.AckEnterTable parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.GameProto.AckEnterTable parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GameProto.AckEnterTable parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GameProto.AckEnterTable parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.GameProto.AckEnterTable prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.AckEnterTable}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.AckEnterTable)
        proto.GameProto.AckEnterTableOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.GameProto.internal_static_proto_AckEnterTable_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.GameProto.internal_static_proto_AckEnterTable_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.GameProto.AckEnterTable.class, proto.GameProto.AckEnterTable.Builder.class);
      }

      // Construct using proto.GameProto.AckEnterTable.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAppendFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        tableId_ = 0;

        if (appendBuilder_ == null) {
          append_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          appendBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.GameProto.internal_static_proto_AckEnterTable_descriptor;
      }

      public proto.GameProto.AckEnterTable getDefaultInstanceForType() {
        return proto.GameProto.AckEnterTable.getDefaultInstance();
      }

      public proto.GameProto.AckEnterTable build() {
        proto.GameProto.AckEnterTable result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.GameProto.AckEnterTable buildPartial() {
        proto.GameProto.AckEnterTable result = new proto.GameProto.AckEnterTable(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.tableId_ = tableId_;
        if (appendBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            append_ = java.util.Collections.unmodifiableList(append_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.append_ = append_;
        } else {
          result.append_ = appendBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.GameProto.AckEnterTable) {
          return mergeFrom((proto.GameProto.AckEnterTable)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.GameProto.AckEnterTable other) {
        if (other == proto.GameProto.AckEnterTable.getDefaultInstance()) return this;
        if (other.getTableId() != 0) {
          setTableId(other.getTableId());
        }
        if (appendBuilder_ == null) {
          if (!other.append_.isEmpty()) {
            if (append_.isEmpty()) {
              append_ = other.append_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAppendIsMutable();
              append_.addAll(other.append_);
            }
            onChanged();
          }
        } else {
          if (!other.append_.isEmpty()) {
            if (appendBuilder_.isEmpty()) {
              appendBuilder_.dispose();
              appendBuilder_ = null;
              append_ = other.append_;
              bitField0_ = (bitField0_ & ~0x00000002);
              appendBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAppendFieldBuilder() : null;
            } else {
              appendBuilder_.addAllMessages(other.append_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.GameProto.AckEnterTable parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.GameProto.AckEnterTable) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int tableId_ ;
      /**
       * <code>int32 tableId = 1;</code>
       */
      public int getTableId() {
        return tableId_;
      }
      /**
       * <code>int32 tableId = 1;</code>
       */
      public Builder setTableId(int value) {
        
        tableId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 tableId = 1;</code>
       */
      public Builder clearTableId() {
        
        tableId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<proto.ModelProto.KeyValue> append_ =
        java.util.Collections.emptyList();
      private void ensureAppendIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          append_ = new java.util.ArrayList<proto.ModelProto.KeyValue>(append_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ModelProto.KeyValue, proto.ModelProto.KeyValue.Builder, proto.ModelProto.KeyValueOrBuilder> appendBuilder_;

      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public java.util.List<proto.ModelProto.KeyValue> getAppendList() {
        if (appendBuilder_ == null) {
          return java.util.Collections.unmodifiableList(append_);
        } else {
          return appendBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public int getAppendCount() {
        if (appendBuilder_ == null) {
          return append_.size();
        } else {
          return appendBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public proto.ModelProto.KeyValue getAppend(int index) {
        if (appendBuilder_ == null) {
          return append_.get(index);
        } else {
          return appendBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder setAppend(
          int index, proto.ModelProto.KeyValue value) {
        if (appendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppendIsMutable();
          append_.set(index, value);
          onChanged();
        } else {
          appendBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder setAppend(
          int index, proto.ModelProto.KeyValue.Builder builderForValue) {
        if (appendBuilder_ == null) {
          ensureAppendIsMutable();
          append_.set(index, builderForValue.build());
          onChanged();
        } else {
          appendBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder addAppend(proto.ModelProto.KeyValue value) {
        if (appendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppendIsMutable();
          append_.add(value);
          onChanged();
        } else {
          appendBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder addAppend(
          int index, proto.ModelProto.KeyValue value) {
        if (appendBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAppendIsMutable();
          append_.add(index, value);
          onChanged();
        } else {
          appendBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder addAppend(
          proto.ModelProto.KeyValue.Builder builderForValue) {
        if (appendBuilder_ == null) {
          ensureAppendIsMutable();
          append_.add(builderForValue.build());
          onChanged();
        } else {
          appendBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder addAppend(
          int index, proto.ModelProto.KeyValue.Builder builderForValue) {
        if (appendBuilder_ == null) {
          ensureAppendIsMutable();
          append_.add(index, builderForValue.build());
          onChanged();
        } else {
          appendBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder addAllAppend(
          java.lang.Iterable<? extends proto.ModelProto.KeyValue> values) {
        if (appendBuilder_ == null) {
          ensureAppendIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, append_);
          onChanged();
        } else {
          appendBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder clearAppend() {
        if (appendBuilder_ == null) {
          append_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          appendBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public Builder removeAppend(int index) {
        if (appendBuilder_ == null) {
          ensureAppendIsMutable();
          append_.remove(index);
          onChanged();
        } else {
          appendBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public proto.ModelProto.KeyValue.Builder getAppendBuilder(
          int index) {
        return getAppendFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public proto.ModelProto.KeyValueOrBuilder getAppendOrBuilder(
          int index) {
        if (appendBuilder_ == null) {
          return append_.get(index);  } else {
          return appendBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public java.util.List<? extends proto.ModelProto.KeyValueOrBuilder> 
           getAppendOrBuilderList() {
        if (appendBuilder_ != null) {
          return appendBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(append_);
        }
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public proto.ModelProto.KeyValue.Builder addAppendBuilder() {
        return getAppendFieldBuilder().addBuilder(
            proto.ModelProto.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public proto.ModelProto.KeyValue.Builder addAppendBuilder(
          int index) {
        return getAppendFieldBuilder().addBuilder(
            index, proto.ModelProto.KeyValue.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.KeyValue append = 2;</code>
       */
      public java.util.List<proto.ModelProto.KeyValue.Builder> 
           getAppendBuilderList() {
        return getAppendFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.ModelProto.KeyValue, proto.ModelProto.KeyValue.Builder, proto.ModelProto.KeyValueOrBuilder> 
          getAppendFieldBuilder() {
        if (appendBuilder_ == null) {
          appendBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.ModelProto.KeyValue, proto.ModelProto.KeyValue.Builder, proto.ModelProto.KeyValueOrBuilder>(
                  append_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          append_ = null;
        }
        return appendBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.AckEnterTable)
    }

    // @@protoc_insertion_point(class_scope:proto.AckEnterTable)
    private static final proto.GameProto.AckEnterTable DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.GameProto.AckEnterTable();
    }

    public static proto.GameProto.AckEnterTable getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AckEnterTable>
        PARSER = new com.google.protobuf.AbstractParser<AckEnterTable>() {
      public AckEnterTable parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AckEnterTable(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AckEnterTable> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AckEnterTable> getParserForType() {
      return PARSER;
    }

    public proto.GameProto.AckEnterTable getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReqEnterTable_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReqEnterTable_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_AckEnterTable_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_AckEnterTable_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngame.proto\022\005proto\032\013model.proto\"A\n\rReqE" +
      "nterTable\022\017\n\007tableId\030\001 \001(\005\022\037\n\006append\030\002 \003" +
      "(\0132\017.proto.KeyValue\"A\n\rAckEnterTable\022\017\n\007" +
      "tableId\030\001 \001(\005\022\037\n\006append\030\002 \003(\0132\017.proto.Ke" +
      "yValueB\013B\tGameProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.ModelProto.getDescriptor(),
        }, assigner);
    internal_static_proto_ReqEnterTable_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ReqEnterTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReqEnterTable_descriptor,
        new java.lang.String[] { "TableId", "Append", });
    internal_static_proto_AckEnterTable_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_AckEnterTable_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_AckEnterTable_descriptor,
        new java.lang.String[] { "TableId", "Append", });
    proto.ModelProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
