// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gate.proto

package proto;

public final class GateProto {
  private GateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BroadCastOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.BroadCast)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>bytes message = 1;</code>
     * @return The message.
     */
    com.google.protobuf.ByteString getMessage();

    /**
     * <code>int32 type = 2;</code>
     * @return The type.
     */
    int getType();

    /**
     * <code>int32 clientId = 3;</code>
     * @return The clientId.
     */
    int getClientId();

    /**
     * <code>int32 channel = 4;</code>
     * @return The channel.
     */
    int getChannel();

    /**
     * <code>int32 club = 5;</code>
     * @return The club.
     */
    int getClub();
  }
  /**
   * <pre>
   * 广播类型 type 值说明:
   *   0 = PERSON  (个人, 按 clientId 发送)
   *   1 = ALL     (全服广播)
   *   2 = CHANNEL (全渠道广播, 按 channel 过滤)
   *   3 = CLUB    (全工会广播, 按 club 过滤)
   * 对应 Java 枚举: gate.connect.handle.not.BroadCastHandle.BroadcastType
   * </pre>
   *
   * Protobuf type {@code proto.BroadCast}
   */
  public static final class BroadCast extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.BroadCast)
      BroadCastOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BroadCast.newBuilder() to construct.
    private BroadCast(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BroadCast() {
      message_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BroadCast();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.GateProto.internal_static_proto_BroadCast_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.GateProto.internal_static_proto_BroadCast_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GateProto.BroadCast.class, proto.GateProto.BroadCast.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString message_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>bytes message = 1;</code>
     * @return The message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMessage() {
      return message_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>int32 type = 2;</code>
     * @return The type.
     */
    @java.lang.Override
    public int getType() {
      return type_;
    }

    public static final int CLIENTID_FIELD_NUMBER = 3;
    private int clientId_;
    /**
     * <code>int32 clientId = 3;</code>
     * @return The clientId.
     */
    @java.lang.Override
    public int getClientId() {
      return clientId_;
    }

    public static final int CHANNEL_FIELD_NUMBER = 4;
    private int channel_;
    /**
     * <code>int32 channel = 4;</code>
     * @return The channel.
     */
    @java.lang.Override
    public int getChannel() {
      return channel_;
    }

    public static final int CLUB_FIELD_NUMBER = 5;
    private int club_;
    /**
     * <code>int32 club = 5;</code>
     * @return The club.
     */
    @java.lang.Override
    public int getClub() {
      return club_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!message_.isEmpty()) {
        output.writeBytes(1, message_);
      }
      if (type_ != 0) {
        output.writeInt32(2, type_);
      }
      if (clientId_ != 0) {
        output.writeInt32(3, clientId_);
      }
      if (channel_ != 0) {
        output.writeInt32(4, channel_);
      }
      if (club_ != 0) {
        output.writeInt32(5, club_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!message_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, message_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (clientId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, clientId_);
      }
      if (channel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, channel_);
      }
      if (club_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, club_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.GateProto.BroadCast)) {
        return super.equals(obj);
      }
      proto.GateProto.BroadCast other = (proto.GateProto.BroadCast) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (getType()
          != other.getType()) return false;
      if (getClientId()
          != other.getClientId()) return false;
      if (getChannel()
          != other.getChannel()) return false;
      if (getClub()
          != other.getClub()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId();
      hash = (37 * hash) + CHANNEL_FIELD_NUMBER;
      hash = (53 * hash) + getChannel();
      hash = (37 * hash) + CLUB_FIELD_NUMBER;
      hash = (53 * hash) + getClub();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.GateProto.BroadCast parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GateProto.BroadCast parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GateProto.BroadCast parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GateProto.BroadCast parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GateProto.BroadCast parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GateProto.BroadCast parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GateProto.BroadCast parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GateProto.BroadCast parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GateProto.BroadCast parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.GateProto.BroadCast parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.GateProto.BroadCast parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.GateProto.BroadCast parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.GateProto.BroadCast prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 广播类型 type 值说明:
     *   0 = PERSON  (个人, 按 clientId 发送)
     *   1 = ALL     (全服广播)
     *   2 = CHANNEL (全渠道广播, 按 channel 过滤)
     *   3 = CLUB    (全工会广播, 按 club 过滤)
     * 对应 Java 枚举: gate.connect.handle.not.BroadCastHandle.BroadcastType
     * </pre>
     *
     * Protobuf type {@code proto.BroadCast}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.BroadCast)
        proto.GateProto.BroadCastOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.GateProto.internal_static_proto_BroadCast_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.GateProto.internal_static_proto_BroadCast_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.GateProto.BroadCast.class, proto.GateProto.BroadCast.Builder.class);
      }

      // Construct using proto.GateProto.BroadCast.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        message_ = com.google.protobuf.ByteString.EMPTY;

        type_ = 0;

        clientId_ = 0;

        channel_ = 0;

        club_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.GateProto.internal_static_proto_BroadCast_descriptor;
      }

      @java.lang.Override
      public proto.GateProto.BroadCast getDefaultInstanceForType() {
        return proto.GateProto.BroadCast.getDefaultInstance();
      }

      @java.lang.Override
      public proto.GateProto.BroadCast build() {
        proto.GateProto.BroadCast result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.GateProto.BroadCast buildPartial() {
        proto.GateProto.BroadCast result = new proto.GateProto.BroadCast(this);
        result.message_ = message_;
        result.type_ = type_;
        result.clientId_ = clientId_;
        result.channel_ = channel_;
        result.club_ = club_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.GateProto.BroadCast) {
          return mergeFrom((proto.GateProto.BroadCast)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.GateProto.BroadCast other) {
        if (other == proto.GateProto.BroadCast.getDefaultInstance()) return this;
        if (other.getMessage() != com.google.protobuf.ByteString.EMPTY) {
          setMessage(other.getMessage());
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getClientId() != 0) {
          setClientId(other.getClientId());
        }
        if (other.getChannel() != 0) {
          setChannel(other.getChannel());
        }
        if (other.getClub() != 0) {
          setClub(other.getClub());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                message_ = input.readBytes();

                break;
              } // case 10
              case 16: {
                type_ = input.readInt32();

                break;
              } // case 16
              case 24: {
                clientId_ = input.readInt32();

                break;
              } // case 24
              case 32: {
                channel_ = input.readInt32();

                break;
              } // case 32
              case 40: {
                club_ = input.readInt32();

                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private com.google.protobuf.ByteString message_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>bytes message = 1;</code>
       * @return The message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getMessage() {
        return message_;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>bytes message = 1;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>bytes message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>int32 type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public int getType() {
        return type_;
      }
      /**
       * <code>int32 type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int clientId_ ;
      /**
       * <code>int32 clientId = 3;</code>
       * @return The clientId.
       */
      @java.lang.Override
      public int getClientId() {
        return clientId_;
      }
      /**
       * <code>int32 clientId = 3;</code>
       * @param value The clientId to set.
       * @return This builder for chaining.
       */
      public Builder setClientId(int value) {
        
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 clientId = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearClientId() {
        
        clientId_ = 0;
        onChanged();
        return this;
      }

      private int channel_ ;
      /**
       * <code>int32 channel = 4;</code>
       * @return The channel.
       */
      @java.lang.Override
      public int getChannel() {
        return channel_;
      }
      /**
       * <code>int32 channel = 4;</code>
       * @param value The channel to set.
       * @return This builder for chaining.
       */
      public Builder setChannel(int value) {
        
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 channel = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearChannel() {
        
        channel_ = 0;
        onChanged();
        return this;
      }

      private int club_ ;
      /**
       * <code>int32 club = 5;</code>
       * @return The club.
       */
      @java.lang.Override
      public int getClub() {
        return club_;
      }
      /**
       * <code>int32 club = 5;</code>
       * @param value The club to set.
       * @return This builder for chaining.
       */
      public Builder setClub(int value) {
        
        club_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 club = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearClub() {
        
        club_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.BroadCast)
    }

    // @@protoc_insertion_point(class_scope:proto.BroadCast)
    private static final proto.GateProto.BroadCast DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.GateProto.BroadCast();
    }

    public static proto.GateProto.BroadCast getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BroadCast>
        PARSER = new com.google.protobuf.AbstractParser<BroadCast>() {
      @java.lang.Override
      public BroadCast parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<BroadCast> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BroadCast> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.GateProto.BroadCast getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_BroadCast_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_BroadCast_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ngate.proto\022\005proto\"[\n\tBroadCast\022\017\n\007mess" +
      "age\030\001 \001(\014\022\014\n\004type\030\002 \001(\005\022\020\n\010clientId\030\003 \001(" +
      "\005\022\017\n\007channel\030\004 \001(\005\022\014\n\004club\030\005 \001(\005B\013B\tGate" +
      "Protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_BroadCast_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_BroadCast_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_BroadCast_descriptor,
        new java.lang.String[] { "Message", "Type", "ClientId", "Channel", "Club", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
