// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hall.proto

package proto;

public final class HallProto {
  private HallProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReqLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ReqLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *证书
     * </pre>
     *
     * <code>bytes cert = 1;</code>
     */
    com.google.protobuf.ByteString getCert();

    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>bytes nickName = 2;</code>
     */
    com.google.protobuf.ByteString getNickName();

    /**
     * <pre>
     *头像信息
     * </pre>
     *
     * <code>bytes avatar = 3;</code>
     */
    com.google.protobuf.ByteString getAvatar();
  }
  /**
   * <pre>
   *请求登录
   * </pre>
   *
   * Protobuf type {@code proto.ReqLogin}
   */
  public  static final class ReqLogin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ReqLogin)
      ReqLoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqLogin.newBuilder() to construct.
    private ReqLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqLogin() {
      cert_ = com.google.protobuf.ByteString.EMPTY;
      nickName_ = com.google.protobuf.ByteString.EMPTY;
      avatar_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              cert_ = input.readBytes();
              break;
            }
            case 18: {

              nickName_ = input.readBytes();
              break;
            }
            case 26: {

              avatar_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.HallProto.internal_static_proto_ReqLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.HallProto.internal_static_proto_ReqLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.HallProto.ReqLogin.class, proto.HallProto.ReqLogin.Builder.class);
    }

    public static final int CERT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString cert_;
    /**
     * <pre>
     *证书
     * </pre>
     *
     * <code>bytes cert = 1;</code>
     */
    public com.google.protobuf.ByteString getCert() {
      return cert_;
    }

    public static final int NICKNAME_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString nickName_;
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>bytes nickName = 2;</code>
     */
    public com.google.protobuf.ByteString getNickName() {
      return nickName_;
    }

    public static final int AVATAR_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString avatar_;
    /**
     * <pre>
     *头像信息
     * </pre>
     *
     * <code>bytes avatar = 3;</code>
     */
    public com.google.protobuf.ByteString getAvatar() {
      return avatar_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!cert_.isEmpty()) {
        output.writeBytes(1, cert_);
      }
      if (!nickName_.isEmpty()) {
        output.writeBytes(2, nickName_);
      }
      if (!avatar_.isEmpty()) {
        output.writeBytes(3, avatar_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!cert_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, cert_);
      }
      if (!nickName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, nickName_);
      }
      if (!avatar_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, avatar_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.HallProto.ReqLogin)) {
        return super.equals(obj);
      }
      proto.HallProto.ReqLogin other = (proto.HallProto.ReqLogin) obj;

      boolean result = true;
      result = result && getCert()
          .equals(other.getCert());
      result = result && getNickName()
          .equals(other.getNickName());
      result = result && getAvatar()
          .equals(other.getAvatar());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CERT_FIELD_NUMBER;
      hash = (53 * hash) + getCert().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.HallProto.ReqLogin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.ReqLogin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.ReqLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.ReqLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.ReqLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.ReqLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.ReqLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HallProto.ReqLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HallProto.ReqLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.HallProto.ReqLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HallProto.ReqLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HallProto.ReqLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.HallProto.ReqLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求登录
     * </pre>
     *
     * Protobuf type {@code proto.ReqLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ReqLogin)
        proto.HallProto.ReqLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.HallProto.internal_static_proto_ReqLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.HallProto.internal_static_proto_ReqLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.HallProto.ReqLogin.class, proto.HallProto.ReqLogin.Builder.class);
      }

      // Construct using proto.HallProto.ReqLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cert_ = com.google.protobuf.ByteString.EMPTY;

        nickName_ = com.google.protobuf.ByteString.EMPTY;

        avatar_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.HallProto.internal_static_proto_ReqLogin_descriptor;
      }

      public proto.HallProto.ReqLogin getDefaultInstanceForType() {
        return proto.HallProto.ReqLogin.getDefaultInstance();
      }

      public proto.HallProto.ReqLogin build() {
        proto.HallProto.ReqLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.HallProto.ReqLogin buildPartial() {
        proto.HallProto.ReqLogin result = new proto.HallProto.ReqLogin(this);
        result.cert_ = cert_;
        result.nickName_ = nickName_;
        result.avatar_ = avatar_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.HallProto.ReqLogin) {
          return mergeFrom((proto.HallProto.ReqLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.HallProto.ReqLogin other) {
        if (other == proto.HallProto.ReqLogin.getDefaultInstance()) return this;
        if (other.getCert() != com.google.protobuf.ByteString.EMPTY) {
          setCert(other.getCert());
        }
        if (other.getNickName() != com.google.protobuf.ByteString.EMPTY) {
          setNickName(other.getNickName());
        }
        if (other.getAvatar() != com.google.protobuf.ByteString.EMPTY) {
          setAvatar(other.getAvatar());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.HallProto.ReqLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.HallProto.ReqLogin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString cert_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *证书
       * </pre>
       *
       * <code>bytes cert = 1;</code>
       */
      public com.google.protobuf.ByteString getCert() {
        return cert_;
      }
      /**
       * <pre>
       *证书
       * </pre>
       *
       * <code>bytes cert = 1;</code>
       */
      public Builder setCert(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cert_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *证书
       * </pre>
       *
       * <code>bytes cert = 1;</code>
       */
      public Builder clearCert() {
        
        cert_ = getDefaultInstance().getCert();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString nickName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>bytes nickName = 2;</code>
       */
      public com.google.protobuf.ByteString getNickName() {
        return nickName_;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>bytes nickName = 2;</code>
       */
      public Builder setNickName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>bytes nickName = 2;</code>
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString avatar_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *头像信息
       * </pre>
       *
       * <code>bytes avatar = 3;</code>
       */
      public com.google.protobuf.ByteString getAvatar() {
        return avatar_;
      }
      /**
       * <pre>
       *头像信息
       * </pre>
       *
       * <code>bytes avatar = 3;</code>
       */
      public Builder setAvatar(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *头像信息
       * </pre>
       *
       * <code>bytes avatar = 3;</code>
       */
      public Builder clearAvatar() {
        
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ReqLogin)
    }

    // @@protoc_insertion_point(class_scope:proto.ReqLogin)
    private static final proto.HallProto.ReqLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.HallProto.ReqLogin();
    }

    public static proto.HallProto.ReqLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqLogin>
        PARSER = new com.google.protobuf.AbstractParser<ReqLogin>() {
      public ReqLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqLogin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqLogin> getParserForType() {
      return PARSER;
    }

    public proto.HallProto.ReqLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AckLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.AckLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *证书
     * </pre>
     *
     * <code>bytes cert = 1;</code>
     */
    com.google.protobuf.ByteString getCert();

    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    int getUserId();

    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>bytes nickName = 3;</code>
     */
    com.google.protobuf.ByteString getNickName();
  }
  /**
   * Protobuf type {@code proto.AckLogin}
   */
  public  static final class AckLogin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.AckLogin)
      AckLoginOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AckLogin.newBuilder() to construct.
    private AckLogin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AckLogin() {
      cert_ = com.google.protobuf.ByteString.EMPTY;
      userId_ = 0;
      nickName_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AckLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              cert_ = input.readBytes();
              break;
            }
            case 16: {

              userId_ = input.readInt32();
              break;
            }
            case 26: {

              nickName_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.HallProto.internal_static_proto_AckLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.HallProto.internal_static_proto_AckLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.HallProto.AckLogin.class, proto.HallProto.AckLogin.Builder.class);
    }

    public static final int CERT_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString cert_;
    /**
     * <pre>
     *证书
     * </pre>
     *
     * <code>bytes cert = 1;</code>
     */
    public com.google.protobuf.ByteString getCert() {
      return cert_;
    }

    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <pre>
     *用户id
     * </pre>
     *
     * <code>int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    public static final int NICKNAME_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString nickName_;
    /**
     * <pre>
     *昵称
     * </pre>
     *
     * <code>bytes nickName = 3;</code>
     */
    public com.google.protobuf.ByteString getNickName() {
      return nickName_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!cert_.isEmpty()) {
        output.writeBytes(1, cert_);
      }
      if (userId_ != 0) {
        output.writeInt32(2, userId_);
      }
      if (!nickName_.isEmpty()) {
        output.writeBytes(3, nickName_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!cert_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, cert_);
      }
      if (userId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (!nickName_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, nickName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.HallProto.AckLogin)) {
        return super.equals(obj);
      }
      proto.HallProto.AckLogin other = (proto.HallProto.AckLogin) obj;

      boolean result = true;
      result = result && getCert()
          .equals(other.getCert());
      result = result && (getUserId()
          == other.getUserId());
      result = result && getNickName()
          .equals(other.getNickName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CERT_FIELD_NUMBER;
      hash = (53 * hash) + getCert().hashCode();
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.HallProto.AckLogin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.AckLogin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.AckLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.AckLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.AckLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.AckLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.AckLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HallProto.AckLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HallProto.AckLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.HallProto.AckLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HallProto.AckLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HallProto.AckLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.HallProto.AckLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.AckLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.AckLogin)
        proto.HallProto.AckLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.HallProto.internal_static_proto_AckLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.HallProto.internal_static_proto_AckLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.HallProto.AckLogin.class, proto.HallProto.AckLogin.Builder.class);
      }

      // Construct using proto.HallProto.AckLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        cert_ = com.google.protobuf.ByteString.EMPTY;

        userId_ = 0;

        nickName_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.HallProto.internal_static_proto_AckLogin_descriptor;
      }

      public proto.HallProto.AckLogin getDefaultInstanceForType() {
        return proto.HallProto.AckLogin.getDefaultInstance();
      }

      public proto.HallProto.AckLogin build() {
        proto.HallProto.AckLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.HallProto.AckLogin buildPartial() {
        proto.HallProto.AckLogin result = new proto.HallProto.AckLogin(this);
        result.cert_ = cert_;
        result.userId_ = userId_;
        result.nickName_ = nickName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.HallProto.AckLogin) {
          return mergeFrom((proto.HallProto.AckLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.HallProto.AckLogin other) {
        if (other == proto.HallProto.AckLogin.getDefaultInstance()) return this;
        if (other.getCert() != com.google.protobuf.ByteString.EMPTY) {
          setCert(other.getCert());
        }
        if (other.getUserId() != 0) {
          setUserId(other.getUserId());
        }
        if (other.getNickName() != com.google.protobuf.ByteString.EMPTY) {
          setNickName(other.getNickName());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.HallProto.AckLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.HallProto.AckLogin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString cert_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *证书
       * </pre>
       *
       * <code>bytes cert = 1;</code>
       */
      public com.google.protobuf.ByteString getCert() {
        return cert_;
      }
      /**
       * <pre>
       *证书
       * </pre>
       *
       * <code>bytes cert = 1;</code>
       */
      public Builder setCert(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cert_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *证书
       * </pre>
       *
       * <code>bytes cert = 1;</code>
       */
      public Builder clearCert() {
        
        cert_ = getDefaultInstance().getCert();
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id
       * </pre>
       *
       * <code>int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        
        userId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString nickName_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>bytes nickName = 3;</code>
       */
      public com.google.protobuf.ByteString getNickName() {
        return nickName_;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>bytes nickName = 3;</code>
       */
      public Builder setNickName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *昵称
       * </pre>
       *
       * <code>bytes nickName = 3;</code>
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.AckLogin)
    }

    // @@protoc_insertion_point(class_scope:proto.AckLogin)
    private static final proto.HallProto.AckLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.HallProto.AckLogin();
    }

    public static proto.HallProto.AckLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AckLogin>
        PARSER = new com.google.protobuf.AbstractParser<AckLogin>() {
      public AckLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AckLogin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AckLogin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AckLogin> getParserForType() {
      return PARSER;
    }

    public proto.HallProto.AckLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ReqRoomListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ReqRoomList)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   *请求玩法列表
   * </pre>
   *
   * Protobuf type {@code proto.ReqRoomList}
   */
  public  static final class ReqRoomList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.ReqRoomList)
      ReqRoomListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ReqRoomList.newBuilder() to construct.
    private ReqRoomList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ReqRoomList() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ReqRoomList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.HallProto.internal_static_proto_ReqRoomList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.HallProto.internal_static_proto_ReqRoomList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.HallProto.ReqRoomList.class, proto.HallProto.ReqRoomList.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.HallProto.ReqRoomList)) {
        return super.equals(obj);
      }
      proto.HallProto.ReqRoomList other = (proto.HallProto.ReqRoomList) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.HallProto.ReqRoomList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.ReqRoomList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.ReqRoomList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.ReqRoomList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.ReqRoomList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.ReqRoomList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.ReqRoomList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HallProto.ReqRoomList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HallProto.ReqRoomList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.HallProto.ReqRoomList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HallProto.ReqRoomList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HallProto.ReqRoomList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.HallProto.ReqRoomList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *请求玩法列表
     * </pre>
     *
     * Protobuf type {@code proto.ReqRoomList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.ReqRoomList)
        proto.HallProto.ReqRoomListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.HallProto.internal_static_proto_ReqRoomList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.HallProto.internal_static_proto_ReqRoomList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.HallProto.ReqRoomList.class, proto.HallProto.ReqRoomList.Builder.class);
      }

      // Construct using proto.HallProto.ReqRoomList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.HallProto.internal_static_proto_ReqRoomList_descriptor;
      }

      public proto.HallProto.ReqRoomList getDefaultInstanceForType() {
        return proto.HallProto.ReqRoomList.getDefaultInstance();
      }

      public proto.HallProto.ReqRoomList build() {
        proto.HallProto.ReqRoomList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.HallProto.ReqRoomList buildPartial() {
        proto.HallProto.ReqRoomList result = new proto.HallProto.ReqRoomList(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.HallProto.ReqRoomList) {
          return mergeFrom((proto.HallProto.ReqRoomList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.HallProto.ReqRoomList other) {
        if (other == proto.HallProto.ReqRoomList.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.HallProto.ReqRoomList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.HallProto.ReqRoomList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.ReqRoomList)
    }

    // @@protoc_insertion_point(class_scope:proto.ReqRoomList)
    private static final proto.HallProto.ReqRoomList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.HallProto.ReqRoomList();
    }

    public static proto.HallProto.ReqRoomList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ReqRoomList>
        PARSER = new com.google.protobuf.AbstractParser<ReqRoomList>() {
      public ReqRoomList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReqRoomList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ReqRoomList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ReqRoomList> getParserForType() {
      return PARSER;
    }

    public proto.HallProto.ReqRoomList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AckRoomListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.AckRoomList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 roomId = 1;</code>
     */
    int getRoomId();

    /**
     * <code>bytes rule = 2;</code>
     */
    com.google.protobuf.ByteString getRule();

    /**
     * <code>bool open = 3;</code>
     */
    boolean getOpen();
  }
  /**
   * Protobuf type {@code proto.AckRoomList}
   */
  public  static final class AckRoomList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.AckRoomList)
      AckRoomListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AckRoomList.newBuilder() to construct.
    private AckRoomList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AckRoomList() {
      roomId_ = 0;
      rule_ = com.google.protobuf.ByteString.EMPTY;
      open_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AckRoomList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              roomId_ = input.readInt32();
              break;
            }
            case 18: {

              rule_ = input.readBytes();
              break;
            }
            case 24: {

              open_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.HallProto.internal_static_proto_AckRoomList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.HallProto.internal_static_proto_AckRoomList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.HallProto.AckRoomList.class, proto.HallProto.AckRoomList.Builder.class);
    }

    public static final int ROOMID_FIELD_NUMBER = 1;
    private int roomId_;
    /**
     * <code>int32 roomId = 1;</code>
     */
    public int getRoomId() {
      return roomId_;
    }

    public static final int RULE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString rule_;
    /**
     * <code>bytes rule = 2;</code>
     */
    public com.google.protobuf.ByteString getRule() {
      return rule_;
    }

    public static final int OPEN_FIELD_NUMBER = 3;
    private boolean open_;
    /**
     * <code>bool open = 3;</code>
     */
    public boolean getOpen() {
      return open_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (roomId_ != 0) {
        output.writeInt32(1, roomId_);
      }
      if (!rule_.isEmpty()) {
        output.writeBytes(2, rule_);
      }
      if (open_ != false) {
        output.writeBool(3, open_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (roomId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, roomId_);
      }
      if (!rule_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, rule_);
      }
      if (open_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, open_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.HallProto.AckRoomList)) {
        return super.equals(obj);
      }
      proto.HallProto.AckRoomList other = (proto.HallProto.AckRoomList) obj;

      boolean result = true;
      result = result && (getRoomId()
          == other.getRoomId());
      result = result && getRule()
          .equals(other.getRule());
      result = result && (getOpen()
          == other.getOpen());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOMID_FIELD_NUMBER;
      hash = (53 * hash) + getRoomId();
      hash = (37 * hash) + RULE_FIELD_NUMBER;
      hash = (53 * hash) + getRule().hashCode();
      hash = (37 * hash) + OPEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOpen());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.HallProto.AckRoomList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.AckRoomList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.AckRoomList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.AckRoomList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.AckRoomList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.HallProto.AckRoomList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.HallProto.AckRoomList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HallProto.AckRoomList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HallProto.AckRoomList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.HallProto.AckRoomList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.HallProto.AckRoomList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.HallProto.AckRoomList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.HallProto.AckRoomList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.AckRoomList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.AckRoomList)
        proto.HallProto.AckRoomListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.HallProto.internal_static_proto_AckRoomList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.HallProto.internal_static_proto_AckRoomList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.HallProto.AckRoomList.class, proto.HallProto.AckRoomList.Builder.class);
      }

      // Construct using proto.HallProto.AckRoomList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        roomId_ = 0;

        rule_ = com.google.protobuf.ByteString.EMPTY;

        open_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.HallProto.internal_static_proto_AckRoomList_descriptor;
      }

      public proto.HallProto.AckRoomList getDefaultInstanceForType() {
        return proto.HallProto.AckRoomList.getDefaultInstance();
      }

      public proto.HallProto.AckRoomList build() {
        proto.HallProto.AckRoomList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.HallProto.AckRoomList buildPartial() {
        proto.HallProto.AckRoomList result = new proto.HallProto.AckRoomList(this);
        result.roomId_ = roomId_;
        result.rule_ = rule_;
        result.open_ = open_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.HallProto.AckRoomList) {
          return mergeFrom((proto.HallProto.AckRoomList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.HallProto.AckRoomList other) {
        if (other == proto.HallProto.AckRoomList.getDefaultInstance()) return this;
        if (other.getRoomId() != 0) {
          setRoomId(other.getRoomId());
        }
        if (other.getRule() != com.google.protobuf.ByteString.EMPTY) {
          setRule(other.getRule());
        }
        if (other.getOpen() != false) {
          setOpen(other.getOpen());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.HallProto.AckRoomList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.HallProto.AckRoomList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int roomId_ ;
      /**
       * <code>int32 roomId = 1;</code>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>int32 roomId = 1;</code>
       */
      public Builder setRoomId(int value) {
        
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 roomId = 1;</code>
       */
      public Builder clearRoomId() {
        
        roomId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString rule_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes rule = 2;</code>
       */
      public com.google.protobuf.ByteString getRule() {
        return rule_;
      }
      /**
       * <code>bytes rule = 2;</code>
       */
      public Builder setRule(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rule_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes rule = 2;</code>
       */
      public Builder clearRule() {
        
        rule_ = getDefaultInstance().getRule();
        onChanged();
        return this;
      }

      private boolean open_ ;
      /**
       * <code>bool open = 3;</code>
       */
      public boolean getOpen() {
        return open_;
      }
      /**
       * <code>bool open = 3;</code>
       */
      public Builder setOpen(boolean value) {
        
        open_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool open = 3;</code>
       */
      public Builder clearOpen() {
        
        open_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.AckRoomList)
    }

    // @@protoc_insertion_point(class_scope:proto.AckRoomList)
    private static final proto.HallProto.AckRoomList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.HallProto.AckRoomList();
    }

    public static proto.HallProto.AckRoomList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AckRoomList>
        PARSER = new com.google.protobuf.AbstractParser<AckRoomList>() {
      public AckRoomList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AckRoomList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AckRoomList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AckRoomList> getParserForType() {
      return PARSER;
    }

    public proto.HallProto.AckRoomList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReqLogin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReqLogin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_AckLogin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_AckLogin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ReqRoomList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ReqRoomList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_AckRoomList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_AckRoomList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nhall.proto\022\005proto\":\n\010ReqLogin\022\014\n\004cert\030" +
      "\001 \001(\014\022\020\n\010nickName\030\002 \001(\014\022\016\n\006avatar\030\003 \001(\014\"" +
      ":\n\010AckLogin\022\014\n\004cert\030\001 \001(\014\022\016\n\006userId\030\002 \001(" +
      "\005\022\020\n\010nickName\030\003 \001(\014\"\r\n\013ReqRoomList\"9\n\013Ac" +
      "kRoomList\022\016\n\006roomId\030\001 \001(\005\022\014\n\004rule\030\002 \001(\014\022" +
      "\014\n\004open\030\003 \001(\010B\013B\tHallProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_ReqLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_ReqLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReqLogin_descriptor,
        new java.lang.String[] { "Cert", "NickName", "Avatar", });
    internal_static_proto_AckLogin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_AckLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_AckLogin_descriptor,
        new java.lang.String[] { "Cert", "UserId", "NickName", });
    internal_static_proto_ReqRoomList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_ReqRoomList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ReqRoomList_descriptor,
        new java.lang.String[] { });
    internal_static_proto_AckRoomList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_AckRoomList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_AckRoomList_descriptor,
        new java.lang.String[] { "RoomId", "Rule", "Open", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
