// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: result.proto

package proto;

public final class ResultProto {
  private ResultProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code proto.Result}
   */
  public enum Result
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <pre>
     *服务空
     * </pre>
     *
     * <code>SERVER_NULL = 1;</code>
     */
    SERVER_NULL(1),
    /**
     * <pre>
     *回复超时
     * </pre>
     *
     * <code>TIME_OUT = 2;</code>
     */
    TIME_OUT(2),
    /**
     * <pre>
     *服务错误
     * </pre>
     *
     * <code>SERVER_ERROR = 3;</code>
     */
    SERVER_ERROR(3),
    /**
     * <pre>
     *桌子配置错误
     * </pre>
     *
     * <code>TABLE_CONFIG_ERROR = 5;</code>
     */
    TABLE_CONFIG_ERROR(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <pre>
     *服务空
     * </pre>
     *
     * <code>SERVER_NULL = 1;</code>
     */
    public static final int SERVER_NULL_VALUE = 1;
    /**
     * <pre>
     *回复超时
     * </pre>
     *
     * <code>TIME_OUT = 2;</code>
     */
    public static final int TIME_OUT_VALUE = 2;
    /**
     * <pre>
     *服务错误
     * </pre>
     *
     * <code>SERVER_ERROR = 3;</code>
     */
    public static final int SERVER_ERROR_VALUE = 3;
    /**
     * <pre>
     *桌子配置错误
     * </pre>
     *
     * <code>TABLE_CONFIG_ERROR = 5;</code>
     */
    public static final int TABLE_CONFIG_ERROR_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Result valueOf(int value) {
      return forNumber(value);
    }

    public static Result forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return SERVER_NULL;
        case 2: return TIME_OUT;
        case 3: return SERVER_ERROR;
        case 5: return TABLE_CONFIG_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Result>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Result> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Result>() {
            public Result findValueByNumber(int number) {
              return Result.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.ResultProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Result[] VALUES = values();

    public static Result valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Result(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.Result)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014result.proto\022\005proto*^\n\006Result\022\013\n\007SUCCE" +
      "SS\020\000\022\017\n\013SERVER_NULL\020\001\022\014\n\010TIME_OUT\020\002\022\020\n\014S" +
      "ERVER_ERROR\020\003\022\026\n\022TABLE_CONFIG_ERROR\020\005B\rB" +
      "\013ResultProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
